name: 'ArgoCD Install App'
description: 'Parses a deployment template and deploys it'
inputs:
  grpc-web:
    description: 'Use "grpc-web" option when login'
    required: false
  server:
    description: 'The argocd server to connect to'
    required: true
  auth-token:
    description: 'Auth token for ArgoCD'
    required: true
  ticket:
    description: 'The ticket number to use (eg. VTHP-123), you can use the ticket action to retrieve this'
    required: true
  version:
    description: 'The version number to set in the helm values'
    required: true
runs:
  using: "composite"
  steps:
    - name: "Install"
      shell: bash
      run: echo "Ticket ${{ inputs.ticket }} Version ${{ inputs.version }}"
