name: 'ArgoCD Install App'
description: 'Parses a deployment template and deploys it'
inputs:
  grpc-web:
    description: 'Use "grpc-web" option when login'
    required: false
  server:
    description: 'The argocd server to connect to'
    required: true
  username:
    description: 'A argocd username'
    required: true
  password:
    description: 'Password for the assigned argocd username'
    required: true
  project:
    description: 'The name of the project (eg. VTHP-123), you can use the ticket action to retrieve this'
    required: true
runs:
  using: "composite"
  steps:
    - name: "Install"
      shell: bash
      run: echo "Ticket ${{ steps.ticket.outputs.ticket }} Version ${{ inputs.version }}"
