name: 'Extracts ticket information from a branch'
description: 'Outputs ticket name, host names for different environments'
inputs:
  environment:
    description: 'The environment name (development, staging, production)'
    required: true
  ref:
    description: 'The branch name'
    required: true
  prefix:
    description: 'The Jira Prefix (VTHP)'
    required: true
    default: 'VTHP'
outputs:
  ticket:
    description: 'The ticket name'
    value: ${{ steps.extract.outputs.ticket }}
  revision:
    description: 'The revision of the commit (Useful for ArgoCD)'
    value: ${{ steps.extract.outputs.revision }}
runs:
  using: "composite"
  steps:
    - name: "Extract"
      shell: bash
      id: extract
      working-directory: ${{ github.action_path }}
      run: ./dist/$(echo "${{runner.os}}" | tr "[:upper:]" "[:lower:]")
      env:
        INPUT_REF: ${{ inputs.ref }}
        INPUT_ENVIRONMENT: ${{ inputs.environment }}
        INPUT_PREFIX: ${{ inputs.prefix }}
