name: Build and publish
on:
  push:
    tags-ignore:
      - "*.*"
    branches:
      - main
      - feat/**

jobs:
  build_argocd:
    name: Build ArgoCD
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup golang
        uses: actions/setup-go@v2
        with:
          go-version: ^1.18
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('./argocd/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Build ArgoCD Install Action
        working-directory: ./argocd
        shell: bash
        run: |
          env GOOS=linux GOARCH=amd64 go build -o dist/linux
#          env GOOS=windows GOARCH=amd64 go build -o dist/windows
#          env GOOS=darwin GOARCH=amd64 go build -o dist/macos
      - name: "Upload Artifacts"
        if: env.DRY_RUN == false
        uses: actions/upload-artifact@v3
        with:
          name: argocd
          path: ./argocd/dist/

  build_ticket:
    name: Build Ticket Vars
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup golang
        uses: actions/setup-go@v2
        with:
          go-version: ^1.18
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('./ticket/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Build Ticket Action
        working-directory: ./ticket
        shell: bash
        run: |
          env GOOS=linux GOARCH=amd64 go build -o dist/linux
#          env GOOS=windows GOARCH=amd64 go build -o dist/windows
#          env GOOS=darwin GOARCH=amd64 go build -o dist/macos
      - name: "Upload Artifacts"
        if: env.DRY_RUN == false
        uses: actions/upload-artifact@v3
        with:
          name: ticket
          path: ./ticket/dist/

  build_slack:
    name: Build Slack
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Get npm cache directory
        id: npm-cache-dir
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - uses: actions/cache@v3
        id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('./slack/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Build Slack Action
        working-directory: ./slack
        shell: bash
        run: |
          npm install
          npm run release
      - name: "Upload Artifacts"
        if: env.DRY_RUN == false
        uses: actions/upload-artifact@v3
        with:
          name: slack
          path: ./slack/dist/

  release:
    name: Release
    runs-on: ubuntu-20.04
    needs: ["build_argocd", "build_ticket", "build_slack"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "Download Ticket Artifacts"
        if: env.DRY_RUN == false
        uses: actions/download-artifact@v3
        id: ticket
        with:
          name: ticket
          path: ./ticket/dist/

      - name: "Download ArgoCD Artifacts"
        if: env.DRY_RUN == false
        uses: actions/download-artifact@v3
        id: frontend
        with:
          name: argocd
          path: ./argocd/dist/

      - name: "Download Slack Artifacts"
        if: env.DRY_RUN == false
        uses: actions/download-artifact@v3
        id: slack
        with:
          name: slack
          path: ./slack/dist/

      - name: "Update Versions"
        uses: paulhatch/semantic-version@v4.0.3
        id: versioning
        with:
          tag_prefix: "v"
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"
          format: "${major}.${minor}.${patch}"
          namespace: ""
          bump_each_commit: true
          short_tags: false

      - name: Create tag
        run: |
          git config --global user.email "${{ github.event.pusher.email }}"
          git config --global user.name "${{ github.event.pusher.name }}"
          git add .
          git commit -m 'release: ${{ steps.versioning.outputs.version }}'
          git tag v${{ steps.versioning.outputs.version }}
          git push origin --tags
#          MAJOR_TAG=$(echo "${{ steps.versioning.outputs.version }}" | sed "s/\..*//")
#          git tag $MAJOR_TAG -f -a -m "Update tag with version ${{ steps.versioning.outputs.version }}"
#          git push origin tag $MAJOR_TAG --force

      - name: "Build Changelog"
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v3.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.versioning.outputs.version }}
          release_name: v${{ steps.versioning.outputs.version }}
          body: ${{ steps.build_changelog.outputs.changelog }}
          draft: false
          prerelease: false
